name: day_calendar_flutter
description: Package of hours of day for flutter.
version: 1.0.2
homepage: https://github.com/RodolfoBonis/DayCalendar

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  date_util: '>=0.1.4 <2.0.0'
  flutter_mobx: '>=1.0.1 <2.0.0'
  mobx: '>=1.0.2+2 <2.0.0'
  intl: '>=0.16.0 <2.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
